### ISSUE TITLE
メンバー募集です

### ISSUE THREAD

**Issue by murakmii** [941/isucon6member#3]
- 参加者属性: 代表,メンバーどちらでも
- 名前: [@bonon0](https://twitter.com/bonon0)
- 学生枠対象か否か: 否
- 使用言語: PHP2年, Ruby1年くらい(最近はこっちです)
- 担当分野: アプリケーション, DB部分. Nginx等は設定程度なら
- 予選参加日: 9/17, 9/18どちらでも
- 予選の参加場所の予定: 出来ればどこかに集まりたい(都内ならどこでも)
- ISUCON参加経験の有無: 有(ISUCON5)

今年も頑張ります！
よろしくお願いします～:pray:

**Comment by sasukeh** [comment]
インフラ(Azure)周り、nodejs、Pythonの担当ができます。もし良ければ私のチームにjoinしてください！
私がそちらのチームに加わることも可能です。

**Comment by murakmii** [comment]
@sasukeh 
ありがとうございます! 是非よろしくお願いします! :kissing_heart:
今は1人なので、チームがどっちかというのはどうなっても大丈夫です。

問題なければ今後の連絡用に、用意したslackチームへの招待メールを送ろうかと思うのですがよろしいですか？

**Comment by sasukeh** [comment]
こっちのチームにjoinで良いですかね？Slackへの招待お待ちしています！

**Comment by murakmii** [comment]
引き続きあと1名様を募集しておりますので、参加してみたい方は是非どうぞ!

**Comment by murakmii** [comment]
そろそろ募集締め切りなのでcloseします。ありがとうございました。
