### ISSUE TITLE
メンバー募集

### ISSUE THREAD

**Issue by k2wanko** [941/isucon6member#5]
- 参加者属性 チーム代表希望
- 名前 コキチーズ [@k2wanko](https://twitter.com/k2wanko)
- 学生枠対象
- 使用言語、年数 Go: 2年
- 担当分野 アプリケーション
- 予選参加日 17予定 都合がつかない場合18も可
- 予選の参加場所の予定 できればLINEオフィスに集まりたい
- ISUCON参加経験の有無  isucon5にGoで参加

２人で申し込んでいますが できれば３人で出たいので募集します
学生枠で出ようと思うので対象の方のみでお願いします。

僕はアプリケーションを担当予定で
もう一人はデータベース周りを担当します。

**Comment by niconegoto** [comment]
@k2wanko まだ空いていますでしょうか？
- 名前 [@niconegoto](https://twitter.com/koki_ide?lang=ja)
- 学生枠対象　
- 使用言語、仕事で使ったことがあるのがRuby Python Goなのでいずれかがいいです。(現在はGo使ってますが暦は一番浅い)
- 担当分野 サーバーサイド希望
- 予選参加日 17希望 18も可
- 予選の参加場所の予定 LINEオフィス可
- ISUCON参加経験の有無 isucon5にGoで参加

是非お願いします〜！

**Comment by k2wanko** [comment]
@niconegoto 空いてるので是非来てください！
連絡手段ですがこっちのチームのslackに招待で大丈夫でしょうか？

**Comment by niconegoto** [comment]
@k2wanko ISUCONの参加歴ないのにコピペしてそのまま貼ってしまっていたのと、17がきびしくなりそうなのですが、それでも大丈夫であればぜひおねがします〜！

**Comment by k2wanko** [comment]
@niconegoto 大丈夫です。GitHubのPublic Emailに招待送っておきます

**Comment by k2wanko** [comment]
集まったので close
